-- Sistema de Amigos: codigo de amigo unico y permanente, solicitudes,
-- amistades y ultima conexion (para Online/Offline sin WebSockets).
--
-- IMPORTANTE: al revisar el repo, `notifications` no existia todavia como
-- tabla ni como sistema real -- el frontend solo tenia un array vacio en
-- memoria (`notifications` en state.js) con un comentario explicito de que
-- "todavia no existe un endpoint real". Esta migracion crea esa tabla por
-- primera vez, generica (no especifica de Amigos), para que cualquier otra
-- funcionalidad futura la reutilice en vez de armar la suya.

-- Codigo de amigo: se agrega nullable primero para poder rellenar los
-- usuarios ya existentes antes de exigir NOT NULL + UNIQUE.
ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS friend_code VARCHAR(12);

-- Backfill para usuarios existentes: codigo derivado de su id + un valor
-- aleatorio, con probabilidad de colision despreciable para el volumen de
-- usuarios de este proyecto. Los usuarios nuevos generan el suyo en el
-- backend (AuthController + FriendCodeGenerator), con reintento si llegara
-- a chocar contra uno existente.
UPDATE public.users
SET friend_code = UPPER(SUBSTRING(MD5(id::text || clock_timestamp()::text || random()::text), 1, 8))
WHERE friend_code IS NULL;

ALTER TABLE public.users
    ALTER COLUMN friend_code SET NOT NULL;

ALTER TABLE public.users
    ADD CONSTRAINT uq_users_friend_code UNIQUE (friend_code);

-- Ultima actividad: se usa para inferir Online/Offline (umbral en el
-- backend) sin necesidad de WebSockets. JwtAuthFilter la actualiza en cada
-- request autenticado (con un margen minimo entre escrituras).
ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITHOUT TIME ZONE;

UPDATE public.users
SET last_active_at = created_at
WHERE last_active_at IS NULL;

ALTER TABLE public.users
    ALTER COLUMN last_active_at SET NOT NULL,
    ALTER COLUMN last_active_at SET DEFAULT CURRENT_TIMESTAMP;

-- Solicitudes de amistad pendientes. Al aceptar, se borra la fila de aca y
-- se crea la amistad en `friendships` (una sola relacion logica entre dos
-- usuarios). Al rechazar o cancelar, se borra sin crear nada.
CREATE TABLE IF NOT EXISTS public.friend_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    receiver_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friend_requests_pair UNIQUE (sender_id, receiver_id),
    CONSTRAINT chk_friend_requests_no_self CHECK (sender_id <> receiver_id)
);

CREATE INDEX IF NOT EXISTS idx_friend_requests_receiver ON public.friend_requests (receiver_id);
CREATE INDEX IF NOT EXISTS idx_friend_requests_sender ON public.friend_requests (sender_id);

-- Amistades confirmadas: una sola fila logica por par de usuarios
-- (user_id_low siempre el menor de los dos ids). Asi la relacion es una
-- sola tanto para consultarla como para borrarla, sin duplicar filas por
-- direccion (A->B / B->A).
CREATE TABLE IF NOT EXISTS public.friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_low BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    user_id_high BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friendships_pair UNIQUE (user_id_low, user_id_high),
    CONSTRAINT chk_friendships_order CHECK (user_id_low < user_id_high)
);

CREATE INDEX IF NOT EXISTS idx_friendships_low ON public.friendships (user_id_low);
CREATE INDEX IF NOT EXISTS idx_friendships_high ON public.friendships (user_id_high);

-- Notificaciones (primera vez que existe una tabla real para esto, ver
-- nota arriba). Generica a proposito (type + actor_user_id + reference_id)
-- para no atarla solo a Amigos: FRIEND_REQUEST y FRIEND_ACCEPTED son sus
-- primeros dos tipos.
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    type VARCHAR(40) NOT NULL,
    actor_user_id BIGINT REFERENCES public.users (id) ON DELETE SET NULL,
    reference_id BIGINT,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(500),
    read boolean NOT NULL DEFAULT false,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_type_ref ON public.notifications (user_id, type, reference_id);
